name: Create VSIX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Package as VSIX
        run: pnpm run package

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: recline-vsix
          path: ./*.vsix
